title: Title
email: your-email@example.com
description: by Authors

baseurl: "/mindoc" # the subpath of your site, e.g. /blog

twitter_username: jekyllrb
github_username:  jekyll

# Build settings

plugins:
  - jekyll-feed

collections:
  mindoc_media:
    output: true
    layout: 'image_description'
